url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Zavier Andrianarivo" # the name of your site, e.g. ACME Corp.
description: "Welcome to my homepage 😄 !" # a short description of your site
remote_theme: https://github.com/zavierand/zavier.github.io
