menu:
# - {name: 'people', url: '/people'}
- {name: 'hobbies', url: '/hobbies'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
# - {name: 'contact', url: '/contact'}

hobbies:
- {name: 'Art', url: 'art'}
- {name: 'Cars', url: 'cars'}
- {name: 'Cooking', url: 'cooking'}
- {name: 'Fashion', url: 'fashion'}
- {name: 'Music', url: 'music'}
- {name: 'Video Games', url: 'video-games'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Probability and Statistics', url: 'prob-stats'}
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Linear Algebra', url: 'linear-algebra'}
- {name: 'Fundamentals of Machine Learning', url: 'fml'}
- {name: 'Deep Learning', url: 'deep-learning'}
- {name: 'Introduction to Robotic Intelligence', url: 'robot-intelligence'}
- {name: 'Computer Vision', url: 'computer-vision'}
- {name: 'Artificial Intelligence', url: 'artificial-intelligence'}
social:
- {icon: 'github', link: 'https://github.com/zavierand'}
- {icon: 'twitter', link: 'https://twitter.com/zavierand'}
- {icon: 'scholar', link: 'https://scholar.google.com/citations?user=5sfTcUAAAAAJ&hl=en'}
- {icon: 'instagram', link: 'https://instagram.com/zavvier'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/zavierand'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
